### ISSUE TITLE
Plugin not loading knife config properly

### ISSUE THREAD

**Issue by milosgajdos** [stevendanna/knife-hacks#7]
For some reason when I tried to play about with these it looks like they're not reading knife config properly:

$ knife backup export
WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory - /etc/chef/client.pem>
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:64:in `rescue in load_signing_key': I cannot read /etc/chef/client.pem, which you told me to use to sign requests! (Chef::Exceptions::PrivateKeyMissing)
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:60:in`load_signing_key'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:34:in `initialize'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/rest.rb:64:in`new'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/rest.rb:64:in `initialize'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/node.rb:570:in`new'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/node.rb:570:in `list'
    from /Users/milosgajdos/.chef/plugins/knife/chef_server_backup.rb:60:in`backup_standard'
    from /Users/milosgajdos/.chef/plugins/knife/chef_server_backup.rb:35:in `nodes'
    from /Users/milosgajdos/.chef/plugins/knife/chef_server_backup.rb:29:in`backup'
    from /Users/milosgajdos/.chef/plugins/knife/chef_server_backup.rb:73:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/knife/core/subcommand_loader.rb:37:in`load'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/knife/core/subcommand_loader.rb:37:in `block in load_commands'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/knife/core/subcommand_loader.rb:37:in`each'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/knife/core/subcommand_loader.rb:37:in `load_commands'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/knife.rb:114:in`load_commands'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/knife.rb:162:in `run'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/lib/chef/application/knife.rb:123:in`run'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.2/bin/knife:25:in `<top (required)>'
    from /usr/bin/knife:23:in`load'
    from /usr/bin/knife:23:in `<main>'

so knife is trying to load client key from /etc/chef/client.pem and ignoring client key configured in knife.rb

**Comment by milosgajdos** [comment]
False alarm
